version: '3.4'

services:
  ewallet.api:
    image: ${DOCKER_REGISTRY-}ewalletapi
    build:
      context: .
      dockerfile: EWallet.Api/Dockerfile
    depends_on:
            - db
  db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            ACCEPT_EULA: "Y"